#Overview
dataset_title
dataset_pubDate
dataset_abstract_para

#PEOPLE
creator_givenName
creator_surName
creator_organizationName
creator_electronicMailAddress
creator_userId
metadataProvider_givenName
metadataProvider_surName
metadataProvider_organizationName
metadata_electronicMailAddress
metadataProvider_userId

#DATES

temporalCoverage_beginDate
temporalCoverage_endDate

#LOCATIONS
geographicCoverage_geographicDescription
geographicCoverage_westBoundingCoordinate
geographicCoverage_eastBoundingCoordinate
geographicCoverage_northBoundingCoordinate
geographicCoverage_southBoundingCoordinate

#TAXA


#METHODS

#NA

dataset_maintenanceUpdateFrequency